-- ============================================================
-- food-log 多用户共享版 · 一次性初始化脚本
-- 用法：Supabase 控制台 → 左侧 SQL Editor → New query
--        → 整段粘贴 → Run
-- 本脚本可重复执行（幂等），改坏了大不了再跑一次。
-- ============================================================

-- ------------------------------------------------------------
-- 1. 记录表
--    entry_date 而非 date（避开关键字，写查询也不用加引号）
--    amount/unit/kcal100 三元组：要么全空、要么齐全合法
--    author_name 默认从登录令牌里取昵称（前端也会显式带上）
-- ------------------------------------------------------------
create table if not exists public.entries (
  id          bigint generated by default as identity primary key,
  entry_date  date        not null,
  meal        text        not null check (meal in ('breakfast','lunch','dinner','snack')),
  name        text        not null check (char_length(name) between 1 and 100),
  calories    int         not null check (calories between 1 and 100000),
  amount      int,
  unit        text,
  kcal100     int,
  author_id   uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  author_name text        not null default coalesce(
                            nullif(current_setting('request.jwt.claims', true), '')::json
                              -> 'user_metadata' ->> 'nickname',
                            '匿名'),
  created_at  timestamptz not null default now(),
  constraint entries_amount_triple check (
    (amount is null and unit is null and kcal100 is null)
    or (amount is not null and unit is not null and kcal100 is not null
        and amount between 1 and 5000
        and unit in ('g','ml')
        and kcal100 between 1 and 2000)
  ),
  constraint entries_author_name_len check (char_length(author_name) between 1 and 40)
);
create index if not exists entries_date_idx on public.entries (entry_date desc);

-- ------------------------------------------------------------
-- 2. 自建食物表（全家共享，名字全库唯一）
--    name_key 由数据库生成（去首尾空白 + 转小写），前端无法伪造
-- ------------------------------------------------------------
create table if not exists public.custom_foods (
  id          bigint generated by default as identity primary key,
  name        text not null check (char_length(name) between 1 and 100),
  name_key    text generated always as (lower(btrim(name))) stored,
  kcal100     int  not null check (kcal100 between 1 and 2000),
  unit        text not null default 'g' check (unit in ('g','ml')),
  author_id   uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author_name text not null default coalesce(
                            nullif(current_setting('request.jwt.claims', true), '')::json
                              -> 'user_metadata' ->> 'nickname',
                            '匿名'),
  created_at  timestamptz not null default now(),
  constraint custom_foods_name_key_uniq unique (name_key),
  constraint custom_foods_author_name_len check (char_length(author_name) between 1 and 40)
);

-- ------------------------------------------------------------
-- 3. 行级安全（RLS）：anon key 是公开的，安全性全靠这里
--    读：所有已登录者（含匿名用户）都能读到全部数据
--    写：只能写自己的（author_id = 当前登录用户）
--    删：只能删自己的
--    改：仅自建食物、且仅限自己的（用于「同名覆盖更新」）
-- ------------------------------------------------------------
alter table public.entries      enable row level security;
alter table public.custom_foods enable row level security;

drop policy if exists entries_select on public.entries;
create policy entries_select on public.entries
  for select to authenticated using (true);

drop policy if exists entries_insert on public.entries;
create policy entries_insert on public.entries
  for insert to authenticated with check (author_id = (select auth.uid()));

drop policy if exists entries_delete on public.entries;
create policy entries_delete on public.entries
  for delete to authenticated using (author_id = (select auth.uid()));

drop policy if exists foods_select on public.custom_foods;
create policy foods_select on public.custom_foods
  for select to authenticated using (true);

drop policy if exists foods_insert on public.custom_foods;
create policy foods_insert on public.custom_foods
  for insert to authenticated with check (author_id = (select auth.uid()));

drop policy if exists foods_delete on public.custom_foods;
create policy foods_delete on public.custom_foods
  for delete to authenticated using (author_id = (select auth.uid()));

drop policy if exists foods_update on public.custom_foods;
create policy foods_update on public.custom_foods
  for update to authenticated
  using (author_id = (select auth.uid()))
  with check (author_id = (select auth.uid()));

-- ------------------------------------------------------------
-- 4. Data API 授权（2026 年起新项目必须显式授权，否则 API 报权限错误）
-- ------------------------------------------------------------
grant usage on schema public to authenticated;
grant select, insert, delete on public.entries to authenticated;
grant select, insert, update, delete on public.custom_foods to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ------------------------------------------------------------
-- 5. Realtime：把两张表加入实时发布
--    replica identity full 是为了让「删除」事件也带全量行数据，
--    否则 RLS 开启时 DELETE 事件可能推不到订阅端
-- ------------------------------------------------------------
alter table public.entries      replica identity full;
alter table public.custom_foods replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.entries;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.custom_foods;
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------
-- 6. 每日清理 + 保活
--    保留含今天共 7 天：删掉 entry_date < 今天-6 的记录
--    任务每天在数据库里跑一次查询，顺带避免免费项目因 7 天无活动被暂停
--    注意 pg_cron 用 UTC 时间：10:23 UTC = 北京时间 18:23（同一自然日）
-- ------------------------------------------------------------
create extension if not exists pg_cron;

select cron.unschedule(jobid) from cron.job where jobname = 'foodlog-cleanup';
select cron.schedule('foodlog-cleanup', '23 10 * * *',
  $$ delete from public.entries where entry_date < current_date - 6 $$);

-- ------------------------------------------------------------
-- 执行成功的标志：界面显示 Success. No rows returned
-- 自查：Table Editor 里能看到 entries / custom_foods 两张空表
-- ------------------------------------------------------------
